# -*- coding: utf-8 -*-
"""Optimization 2 Towards Gradient Descent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14IOsFhUydV512tr3H9jnwy8hRDR8QBlk

## Content
- Recap
- Differentiation geomtric picture
- How to find derivative for any given function
  - Examples of finding derivatives of some functions
- How to check if a function is differentiable
  - Checking differentiability of few functions
- Commonly used derivatives
- Rules of differentiation
  - Linearity rule
  - Product rule
  - Quotient rule
  - Chain rule
- How do we use derivatives for optimization
  - How to identify critical points for any function
  - How to indentify if a critical point is minima or maxima

## Recap

We learnt about the optimization equation in the last class now let's quickly understand it from an example

We want to find the value of x which maximizes the function $-(x-2)^2$

As we can see that the maximum value for this function is 0

Q. What is the value of x at which this maximum value occurs?
  - it is x=2 as we can see from the plot

![](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/048/559/original/Screenshot_2023-09-15_at_12.25.20_PM.png?1694760940)

![](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/048/560/original/Screenshot_2023-09-15_at_12.26.24_PM.png?1694761000)

## Differentiation geometric picture

Let's say we have 2 points on the line $(x_1, y_1)$ and $(x_2, y_2)$

Q. What is the slope of this line?
- it would be $tan(\theta)=\frac{y_2-y_1}{x_2-x_1}$

![](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/048/561/original/Screenshot_2023-09-15_at_12.36.09_PM.png?1694761590)

Now let's see what will happen if we have a complicated curve and not a straight line

- let this be a function $y=f(x)$
- For the two points we can create a line which connect both the point on that curve which means that it is passing through both the points is also making angle with the x axis but do you also notice a gap between the line and the curve/ function.
- Now we can get the slope of the points the same way we did earlier which is $\frac{y_2-y_1}{x_2-x_1}$

**Q. Can we rename the points as follows**
  - $(x_2,y_2) ->(x_2,f(x_2)) $
  - $(x_1,y_1) ->(x_1,f(x_1)) $
  - Yes we can as they mean the same thing

now using this notation our slope equation becomes
- $\frac{f(x_2)-f(x_1)}{x_2-x_1}$

![](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/048/567/original/Screenshot_2023-09-15_at_12.44.31_PM.png?1694762087)

Let's call point $(x1,f(x_1))$ as point A and $(x2,f(x_2))$ as point B

Let's fix point A and and we start changing the point B and come closer to point A we keep doing this untill the new point is very very close to out exisiting point A

So esentially this new poitn would be slightly greater than A ie it'll have a value of x and f(x) slightly greater than x this slight difference we call it as $\Delta x$ and we'll represent this new point as $(x+\Delta x)$ and the correspoinding y value would become $f(x_1+\Delta x)$

Next we would find the slope between the point A and the new point closer to point A
- the slope would be $\frac{f(x+\Delta x)-f(x_1)}{\Delta x}$

What are we trying to find out here?
- we are trying to find out a line between 2 points which are very very very close to each otherand we say that the value of $\Delta x$ approached 0

![](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/048/571/original/Screenshot_2023-09-15_at_1.01.35_PM.png?1694763114)

**Terminologies**

- If a line joins any 2 points on a function curve we call that as a **secant**
- If a line touches only 1 points on a function or curve we call that as a **Tangent**

This tangents are very imporant and they help us get the derivatives let's see how
- Let's say we have a function with the curve as shown and we have a point $(x_1, f(x_1))$ on this curve
- Now to define the derivate what we do is we define a tangent that touches this point $x_1$
- Thus the derivate of a function $f(x)$ at $x=x_1$ and is nothing but the slope of the tangent at that point $x_1$
  - $f'(x_1)=L_{\Delta x->0}\frac{f(x+\Delta x)-f(x_1)}{\Delta x}$
  - here we are using limit as as $\Delta x$ approached 0 because what we want is as this difference becomes smaller and smaller we'll reach to a point where it is touching the curve at only one single point which is nothing but our tanget and at that point we'll be checking what the slope is.
  
Now the slope at point $x_1$ will have some positive value of slope now what will be the slope at point $x_2$?
- it'll be 0

![](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/048/585/original/Screenshot_2023-09-15_at_1.15.08_PM.png?1694763927)

**Note:**
- $\Delta x$ is also represented as $\delta x$ at many places but they refer to the same thing in this context

## How to find derivative for any given function

The simplest way to finding the derivative of a function is use th defination that we saw above this is known as *Ab initio method*
- $\frac{d}{dx}f(x_1)=f'(x)=L_{\Delta x \to 0}\frac{f(x+\Delta x)-f(x_1)}{\Delta x}$
- if you see a notation as $f''(x_1)$ it means that we have take derivative 2 times

The second method which we'll be using is we'll rememebr the derivatives of some well known function and then use them and some rules when deriving the derivatives of unkownn functions.

![](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/048/589/original/Screenshot_2023-09-15_at_1.23.51_PM.png?1694764446)

### Examples of finding derivatives of some functions

#### $f(x)=x^2$

we'll us the standard defination of derivatives

We know that

$f'(x) = \lim_{x \to 0} \frac{f(x+Δx) - f(x)}{Δx}$

$= \lim_{x \to 0} \frac{(x+Δx)^2 - x^2}{Δx}$

$= \lim_{x \to 0} \frac{(Δx)^2 + 2x(Δx)}{Δx}$

$= \lim_{x \to 0} Δx + 2x$

$= 2x$

![](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/048/591/original/Screenshot_2023-09-15_at_1.32.38_PM.png?1694764974)

##### Finding derivative using code

Let's look at how we can find this using code
"""

import numpy as np
import matplotlib.pyplot as plt

def plot_function(func):
  x_values = np.linspace(-10, 10, 1000)
  y_values = [func(x) for x in x_values]

  plt.plot(x_values, y_values)

plot_function(lambda x: x**2)

"""Now let's write another function `plot_derivative()`"""

def plot_derivative(func):
  x_values = np.linspace(-10, 10, 1000)
  # delta has to be close to 0, but cannot be 0, that would give division by 0
  delta = 0.0001

  y_values = (func(x_values + delta) - func(x_values)) / delta

  plt.plot(x_values, y_values)

plot_derivative(lambda x: x**2)

"""Observe that this plot is following the function $g(x) = 2x$, which is exactly what we evaluated as $f'(x)$.

**Let's remember some rules to solve a function which is in the form of $(x)^n$**
- to compute the derivative of such function what we do is we bring down the n in front of the x variable and subtract 1 from the power to get the final value of the derivative.
- $\frac{d}{dx}f(x)^n=n.x^{n-1}$

![](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/048/612/original/Screenshot_2023-09-15_at_2.12.22_PM.png?1694767403)

#### $f(x)=x$ and $f(x)=-x$

Q. if $f(x)=x$ then what is $f'(x)$
- it is 1 because we can write x as $x^1$ and solving this we would get the value as 1

Q. if $f(x)=-x$ then what is $f'(x)$
- it is -1

![](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/048/613/original/Screenshot_2023-09-15_at_2.15.36_PM.png?1694767550)

#### $f(x)=\left|x\right|$

The defination of this mod function is
- for all the values where x is greater than 0 y=x
- for all the values where x is less than 0 y=-x
  - here -x is because for let say f(-10) the corresponsing value of y is +10
  - thus when we take negative of x we'll get 10 hence -(x) we'll get -(-10) which is 10
- for x=0 y=0

We can divide the area into 2 parts one which belongs to $y=x$ and other that belogs to $y=-x$

So in this case we can create 3 cases to find the derivatives of this function

**Case 1:**
- $f(x)=x$ then the derivative of this function at x will be 1 we have already learnt this

**Case 2**:
- the derivative of function f(x)=-x will be -1 we can also solve this usign the standard defination of derivative

**Case 3:**
- Q. Can we say that the function is continuous at x=0?
  - yes we can say that it is continuous as right hand limit as x tends to 0 will be equal to left hand limit as x tends to 0 will be equal to the value of f(x) as x=0 all will be equal
- Now differentiability at this point can be defined as
  - we will find out $L_{x \to 0^+}f'(x)$ which is what is the value as x tends to 0 from positive side on the derivative of the function, which is equal to 1
  - and we will also find out $L_{x \to 0^-}f'(x)$ which is what is the value as x tends to 0 from negagive side on the derivative of the function, which is equal to -1
  - so we can say that this function is non-differentiable at point x=0

![](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/048/619/original/Screenshot_2023-09-15_at_2.32.57_PM.png?1694768595)

**Let's intutively understand what differentiation is**

Let say you are at point A and want to travel to point B
- Let the distance from point a to point B be x

Now we want to find out how quickly he reached point B in some amount fo time so what are we esentially finding here?
- we are finding the speed
- so if we have a function of distance $f(x)=x$ then we can take the derivate to find out how the distance is changing with respect to time which is rerpesented as $\frac{d}{dt}(x)$
- Now let say you are sitting in a car then we are never moving at a constant speed either we are accelerating or decelerating so if we were to find out the rate of change of speed with respect to time this is nothing but acceleration
  - we'll get this by taking second derivaite on top of the previous derivaite hence we represent it as $f''(x)$=$\frac{d}{dt}f'(x)$

Do you remember the laws on motion in your high school ?
- if not don't worry we wont go there but do you remember an eqaution as $s=ut+1/2at^2$
  - where u= inital velocity
  - t is the time
  - a is the acceleration

Now we waant to find out what is $\frac{d}{dt}s$, lets see how to get this
- where getting a derivate of a constant multiplied with a varaible like 2x we take the constant out and then compute the derivative of that variable
  - so derivative of $ut$ with respect to $t$ would be equal to $u\frac{d}{dt}t$ which is eual to $u$
- next $1/2a$ will act as a constant and $t^2$ is our variable so the derivate of this is as follows:
  - $1/2a\frac{d}{dt}t^2$
  - 2/2.a.t
  - at

thus $\frac{d}{dt}s=u+at$

and the second derivative would be represented as
- $\frac{d^2}{dt^2}s=a$

![](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/048/626/original/Screenshot_2023-09-15_at_3.12.40_PM.png?1694770975)

## How to check if a function is differentiable

**Steps**
1. we will find out the value of first derivative of the function ie $f'(x)$
2. Find out if the values are continuous or discontinuous at $f'(x)$
  - For this we have to create a plot of $f'(x)$ and then check whether it is continuous or discontinuous
  - **So if $f'(x)$ is discontinuous then we say that $f(x)$ is not differentiable**

![](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/048/893/original/Screenshot_2023-09-18_at_11.39.39_AM.png?1695017394)

### checking differentiability for $f(x)=\left|x\right|$

Let's understand the same concept visually via the tangents concept and checking of function $f(x)=\left|x\right|$ is differentiable or not

When we say that a function is differentiable we say that we can find out the slope of the tangent

Q. Now for the given function $f(x)=\left|x\right|$ at point $x=0$ can we find the slope?
- Your first question should be how should we create this tanget as you can see that there can be multiple tangets possible at this point.
- Because of this we say that at point $x=0$ we cannot differentiate the function $f(x)=\left|x\right|$

Mathematically we'll do something as follows based on the above mentioned steps
- We'll first take the first derivate of the function $f(x)$
  - it'll be +1 where values of x is greater than 0
  - it'll be -1 where values of x is less than 0
  - And we cannot differentiat at x=0
- Thus we say that the function $f'(x)$ is discontinuous and hence the function $f(x)$ is not differentiable

![](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/048/894/original/Screenshot_2023-09-18_at_11.47.43_AM.png?1695017880)

Q. From the given below function identify the function which is non differentiable.
- Note that these are $f(x)$ and not $f'(x)$

![](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/048/895/original/Screenshot_2023-09-18_at_11.49.20_AM.png?1695017975)

- The correct answer is 2 and 3
  - for function 2 we can have multiple tangets at the point where the function is dipping
  - for function 3 is itself a discontinuous function hence it cannot be differentiated

![](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/048/896/original/Screenshot_2023-09-18_at_11.52.07_AM.png?1695018141)

### checking differentiability for $f(x)=x^2$

![](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/048/897/original/Screenshot_2023-09-18_at_12.12.53_PM.png?1695019390)

in the plot $f'(x)$ we are essentially tracking what is the slope for different values of x and this is how the plot is generated in the first place

## Commonly used derivatives

![](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/048/901/original/Screenshot_2023-09-18_at_12.22.19_PM.png?1695019955)

## Rules of differentiation

### Linearity rule

if we have a function $h(x)=g(x)+f(x)$ and we want to find the derivative of $h(x)$
- To calculate this we'll simply find the deeriavte of the two functions $g(x)$ and $f(x)$ and simple add them
- hence $h'(x)=g'(x)+f'(x)$

Example: $f(x)=x^3+log(x)$
- $f'(x)=3x^2+\frac{1}{x}$

![](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/048/903/original/Screenshot_2023-09-18_at_12.29.14_PM.png?1695020369)

There is another case where to a function we multiply a constant value
ie $h(x)=c.f(x)$ where $c \in \mathbb{R}$
- to find the derivate in this case we keep the c as it is and we'll finc the deriavtive of $f(x)$
- $h'(x)=c.f'(x)$

**Example:**
- $f(x)=3.sin(x)$
  - $f'(x)=3.cos(x)$

![](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/048/904/original/Screenshot_2023-09-18_at_12.34.17_PM.png?1695020674)

### Product rule

Let say we have a function $h(x)=g(x).f(x)$ how would we find out the derivative of $h(x)$?
- In this case we take $g(x)$ as constant and find the derivate of $f(x)$ plus take $f(x)$ as constant and find the derivate of $g(x)$
- thus $h'(x)=f'(x).g(x)+f(x).g'(x)$

![](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/048/905/original/Screenshot_2023-09-18_at_12.38.54_PM.png?1695020953)

### Quotient rule

Here we have 2 functions which are being divided so $h(x)=\frac{f(x)}{g(x)}$
- To find the derivatie of $h(x)$ here are the steps
  1. First we find the derivate of numerator and keep the denominator as it is
  2. then we keep the numerator as it is and find the derivative of numerator
  3. we subtract results of step 1 and 2
  4. divide result in step 3 by $[g(x)]^2$

![](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/048/907/original/Screenshot_2023-09-18_at_12.55.19_PM.png?1695021935)

### Chain rule

Let say we have a function $h(x)$ which is defined as a function inside a functio ie $h(x)=f(g(x))$ and to find the derivate of $h(x)$ below are the steps
1. keep $g(x)$ as a constant and find derivative of $f(x)$
2. Multiply the result of step 1 with deriavtive of $g(x)$

![](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/048/908/original/Screenshot_2023-09-18_at_12.59.06_PM.png?1695022163)

## How do we use derivatives for optimization

For the given curve
- all the points to the left of point 1 will have a negative slope
- similarly for point 3 and 5 we'll have a negative slope for all the points to the left of point 3 and 5

And
- all the points to the right of point 1 will have a positive slope
- similarly for point 3 and 5 we'll have a positive slope for all the points to the right of point 3 and 5

For points 2 and 4
- on the left side we'll have a positive slope and on the right side we'll have negative slopes for all the points

Now we call all this 5 points as **critical points** where the sign of the slope is changing
- For points 1, 3 and 5 we can observe that the slope is changing from negative to positive and we call this points as **Minima**
- For points 2 and 4 we can observe that the slope is changing from  positive to negative and we call this points as **Maxima**

![](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/048/912/original/Screenshot_2023-09-18_at_1.18.26_PM.png?1695023321)

### How to identiy critical points for any function

Q. for the above function what is the slope or derivative at point 1,2,3,4 and 5?
- It is 0

Q. Out of points 1,3 and 5 which point is the lowest?
- it is point 1 we call this point as the **global minima** and the points 3 and 5 are called as the **local minima** of the function

Q. Out of points 2 and 4 which point has the highest peak or value?
- it is point 4 we call this point as the **global maxima** and the points 2 is called as the **local maxima** of the function

So to identiy critical points of any given function we find the point where derivate is equal to 0 and at that point the function would be flat

![](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/048/918/original/Screenshot_2023-09-18_at_1.31.55_PM.png?1695024132)

### How to indentify if a critical point is minima or maxima

One way to is as follows:
- let say we want to identiy if point 1 is minima or maxima what we can do is we take another point which very close and left of point 1 and find the slope
- and similarly we take another point which is very close and to the right side of point 1 and find the slope
- next we verify if the change in slope if from negative to positive from left to right then it is minima and if the change in slope is from positive to negative then it is a maxima

But this is a tedious and a length process

Second way is to take a second derivate at all those critical points
Now the second derivate can give us 3 possible values
1. $f''(x)>0$ ie the second derivative is positive then we say that we have reached a **minima**
2. $f''(x)<0$ ie the second derivative is negative then we say that we have reached a **maxima**
3. $f''(x)=0$ ie the second derivative is positive then we say that we have reached a **Saddle point**

When we looked at the plot of the first derivative of the slope we learnt that it is nothing but the slope at different values of x now when we look at the second derivate esentially what we are finding out is the **rate of change of slopes**

![](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/048/923/original/Screenshot_2023-09-18_at_2.13.49_PM.png?1695026641)

Let's analyze the curve that we saw earlier for point 1
- For point 1 we saw that the slopes is going from negative to positive ie for example from -3,-2,-1,0,1,2,3
- Now to go from -3 to -2 we are adding a 1 to it so esentially we are changing the slope by adding a value similarly for rest of the points
- So we can say that there is a positive change of rate of slopes from -3 to 3 which means that the double derivate is positive
- **Thus when there is a positive rate of change in slopes then it will be a minima**

Let's analyze the curve that we saw earlier for point 2
- For point 2 we saw that the slopes is going from positive to negative ie for example from 3,2,1,0,-1,-2,-3
- Now to go from -3 to -2 we are subtracting by -1 to it so esentially we are changing the slope by subtracting a value similarly for rest of the points.
- So we can say that there is a negative change of rate of slopes from 3 to -3 which means that the double derivate is negagive
- **Thus when there is a negative rate of change in slopes then it will be a maxima**

![](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/048/926/original/Screenshot_2023-09-18_at_2.23.43_PM.png?1695027237)

**What is a Saddle point?**
- Let say we have a curve as shown
- For the marked point do you see that the slope is 0
- Points to the left of this point will have a negative slope and points to the right side will also have a negative slope thus the signs are not changing
- We call this points as **Saddle points**
- These are points where the derivative is 0 but they are neither maxima or minima

![](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/048/927/original/Screenshot_2023-09-18_at_2.28.38_PM.png?1695027536)

For the given function determines whether point 1,2 and 3 are minima, maxima or a saddle point

![](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/048/928/original/Screenshot_2023-09-18_at_2.35.27_PM.png?1695027939)
"""

